# Generated by Django 5.1 on 2024-09-22 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(default=None, max_length=100)),
                ('doctor', models.CharField(default=None, max_length=100)),
                ('date', models.CharField(default=None, max_length=100)),
                ('time', models.CharField(default=None, max_length=100)),
                ('hospitalName', models.CharField(default=None, max_length=100)),
                ('branch', models.CharField(default=None, max_length=100)),
                ('specialisation', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('email', models.EmailField(default=None, max_length=100)),
                ('phoneNumber', models.CharField(default=None, max_length=20)),
                ('age', models.IntegerField(default=None)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=None, max_length=6)),
                ('password', models.CharField(default=None, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorName', models.CharField(default=None, max_length=100)),
                ('email', models.EmailField(default=None, max_length=100)),
                ('phoneNumber', models.CharField(default=None, max_length=20)),
                ('age', models.IntegerField(default=None)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=None, max_length=6)),
                ('specialisation', models.CharField(choices=[('oncology', 'oncology'), ('nephrology', 'nephrology'), ('neurology', 'neurology'), ('cardiology', 'cardiology'), ('gastroenterology', 'gastroenterology')], default=None, max_length=30)),
                ('hospitalName', models.CharField(choices=[('star hospitals', 'star hospitals'), ('yashoda hospitals', 'yashoda hospitals'), ('apollo hospitals', 'apollo hospitals'), ("kim's hospitals", "kim's hospitals"), ('care hospitals', 'care hospitals')], default=None, max_length=30)),
                ('branch', models.CharField(choices=[('banjara Hills', 'banjara Hills'), ('secunderabad', 'secunderabad'), ('jubilee Hills', 'jubilee Hills'), ('malakpet', 'malakpet'), ('gachibowli', 'gachibowli')], default=None, max_length=30)),
                ('time', models.CharField(default=None, max_length=30)),
                ('password', models.CharField(default=None, max_length=20)),
            ],
        ),
    ]
