# Generated by Django 5.1 on 2024-09-22 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppointmentGuru', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointments',
        ),
    ]
