# Generated by Django 5.1 on 2024-09-22 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppointmentGuru', '0002_delete_appointments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorName', models.CharField(default=None, max_length=100)),
                ('patientName', models.CharField(default=None, max_length=100)),
                ('date', models.CharField(default=None, max_length=100)),
                ('time', models.CharField(default=None, max_length=100)),
                ('hospitalName', models.CharField(default=None, max_length=100)),
                ('branch', models.CharField(default=None, max_length=100)),
                ('specialisation', models.CharField(default=None, max_length=100)),
            ],
        ),
    ]
