# Generated by Django 5.1 on 2024-09-22 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppointmentGuru', '0003_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patientMailId',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='branch',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.CharField(default=None, max_length=15),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctorName',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='hospitalName',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patientName',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='specialisation',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
