# Generated by Django 5.1 on 2024-09-13 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppointmentGuru', '0003_doctor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
