# Generated by Django 5.1 on 2024-09-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppointmentGuru', '0004_appointment_patientmailid_alter_appointment_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctorMailId',
            field=models.CharField(default=None, max_length=150),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patientPhoneNo',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
