# Generated by Django 5.1 on 2024-09-13 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AppointmentGuru', '0004_delete_customer_delete_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('email', models.EmailField(default=None, max_length=100)),
                ('phoneNumber', models.CharField(default=None, max_length=20)),
                ('age', models.IntegerField(default=None)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=None, max_length=6)),
                ('password', models.CharField(default=None, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctorName', models.CharField(default=None, max_length=100)),
                ('email', models.EmailField(default=None, max_length=100)),
                ('phoneNumber', models.CharField(default=None, max_length=20)),
                ('age', models.IntegerField(default=None)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default=None, max_length=6)),
                ('time', models.CharField(default=None, max_length=30)),
                ('password', models.CharField(default=None, max_length=20)),
                
            ],
        ),
    ]
