# Generated by Django 5.1 on 2024-09-23 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppointmentGuru', '0005_appointment_doctormailid_appointment_patientphoneno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='patientPhoneNo',
            new_name='doctorPhoneNumber',
        ),
        migrations.AddField(
            model_name='appointment',
            name='patientPhoneNumber',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
