# Generated by Django 5.1 on 2024-09-13 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppointmentGuru', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='branch',
            field=models.CharField(choices=[('banjara Hills', 'banjara Hills'), ('secunderabad', 'secunderabad'), ('jubilee Hills', 'jubilee Hills'), ('malakpet', 'malakpet'), ('gachibowli', 'gachibowli')], default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='doctor',
            name='hospitalName',
            field=models.CharField(choices=[('star hospitals', 'star hospitals'), ('yashoda hospitals', 'yashoda hospitals'), ('apollo hospitals', 'apollo hospitals'), ("kim's hospitals", "kim's hospitals"), ('care hospitals', 'care hospitals')], default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialisation',
            field=models.CharField(choices=[('oncology', 'oncology'), ('nephrology', 'nephrology'), ('neurology', 'neurology'), ('cardiology', 'cardiology'), ('gastroenterology', 'gastroenterology')], default=None, max_length=30),
        ),
    ]
