# Generated by Django 5.1 on 2024-09-20 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppointmentGuru', '0006_doctor_branch_doctor_hospitalname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='customer',
            field=models.ManyToManyField(to='AppointmentGuru.customer'),
        ),
    ]
