# Generated by Django 5.1 on 2024-09-24 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppointmentGuru', '0006_rename_patientphoneno_appointment_doctorphonenumber_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospitalName', models.CharField(default=None, max_length=50)),
                ('branch', models.CharField(default=None, max_length=30)),
                ('code', models.CharField(default=None, max_length=15)),
            ],
        ),
    ]
