# Generated by Django 5.1 on 2024-09-20 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppointmentGuru', '0007_doctor_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='customer',
        ),
        migrations.AddField(
            model_name='customer',
            name='doctor',
            field=models.ManyToManyField(to='AppointmentGuru.doctor'),
        ),
    ]
