# Generated by Django 5.1 on 2024-09-25 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppointmentGuru', '0008_alter_appointment_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='time',
            field=models.CharField(default=None, max_length=40),
        ),
    ]
