# Generated by Django 5.1 on 2024-09-20 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppointmentGuru', '0008_remove_doctor_customer_customer_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='doctor',
        ),
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(default='', max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppointmentGuru.customer')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppointmentGuru.doctor')),
            ],
        ),
    ]
