# Generated by Django 5.1 on 2024-09-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppointmentGuru', '0009_alter_doctor_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='branch',
            field=models.CharField(choices=[('banjara hills', 'banjara Hills'), ('secunderabad', 'secunderabad'), ('jubilee hills', 'jubilee Hills'), ('malakpet', 'malakpet'), ('gachibowli', 'gachibowli')], default=None, max_length=30),
        ),
    ]
