# Generated by Django 5.1 on 2024-11-04 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppointmentGuru', '0010_alter_doctor_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='max_patients_per_slot',
            field=models.IntegerField(default=5),
        ),
    ]
